package SeleniumBasics;
// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class AdidasTest {
    private WebDriver driver;

    @BeforeClass
    public void setUp() {
        driver = new ChromeDriver();
       }

    @AfterClass
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void abc() throws InterruptedException {
        driver.get("https://www.flipkart.com/");
        Thread.sleep(2000);
        //driver.manage().window().setSize(new Dimension(1524, 804));
        //driver.findElement(By.name("q")).click();
        //driver.findElement(By.name("q")).sendKeys("watch");
        //Thread.sleep(2000);
        //driver.findElement(By.cssSelector(".L0Z3Pu > svg")).click();

        //Thread.sleep(5000);
    }


    @Test
    public void xyz() throws InterruptedException {
        System.out.println();
    }
}
